services:
  sim_franka_humble:
    image: hucebot:franka-humble
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sim_franka_humble
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=39
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./franka_bringup:/home/user/humble_ws/src/bimanual_architecture/franka_bringup
      - ./franka_example_controllers:/home/user/humble_ws/src/bimanual_architecture/franka_example_controllers
      - ./franka_simple_publishers:/home/user/humble_ws/src/bimanual_architecture/franka_simple_publishers
      - ./franka_description:/home/user/humble_ws/src/bimanual_architecture/franka_description